(function(){
  var headerHost=document.querySelector('[data-site-header]'),footerHost=document.querySelector('[data-site-footer]');
  if(headerHost)headerHost.innerHTML='<header class="site-header"><div class="inner"><a class="logo" href="index.html" aria-label="A Creative Block home"><span class="acb-logo-mount" data-beta-logo data-acb-logo="3lines" data-acb-mode="eye" style="display:inline-block;height:66.6px;color:#4F46E5;vertical-align:middle"></span></a><div class="hdr-right"><div class="hdr-top"><span class="clock">Lisbon · online worldwide</span><a href="../games/index.html">Playroom</a><a href="faq.html">FAQ</a><a href="resources.html">Resources</a><a href="mailto:hello@acreativeblock.com">Support us</a><a class="pill" href="mailto:hello@acreativeblock.com">Book a session</a></div><div class="hdr-divider"></div><nav class="hdr-main" aria-label="Main navigation"><span class="menu navitem"><button class="navbutton">Work with us ↓</button><span class="submenu mega"><a href="individuals.html"><strong>For individuals</strong></a><a href="organisations.html"><strong>For organisations</strong></a><a href="index.html#offers"><strong>Formats &amp; pricing</strong></a></span></span><span class="menu navitem"><button class="navbutton">What gets in the way ↓</button><span class="submenu mega"><a href="blocks.html"><strong>The block map</strong></a><a href="evidence.html"><strong>Evidence &amp; boundaries</strong></a></span></span><span class="menu navitem"><button class="navbutton">How we work ↓</button><span class="submenu mega"><a href="method.html"><strong>The CRAFT method</strong></a><a href="method.html#response"><strong>Coaching &amp; consulting</strong></a><a href="faq.html"><strong>FAQ</strong></a></span></span><a href="manifesto.html">Manifesto</a><a href="about.html">About</a><a href="mailto:hello@acreativeblock.com">Contact</a></nav></div></div></header>';
  if(footerHost)footerHost.innerHTML='<footer class="footer"><div class="wrap"><div class="footer-lead"><p class="footer-statement">For anyone with a project that matters. Understand what is stopping the work, then match the response to what is actually happening.</p><div><h3>Occasional updates</h3><p>Research, practical ideas and news from A Creative Block.</p><form class="newsletter"><input type="email" placeholder="Your email" aria-label="Email"><button>Join →</button></form></div></div><div class="footer-cols"><div><h3>Work with us</h3><a href="individuals.html">Individuals</a><a href="organisations.html">Organisations</a><a href="individuals.html#public">Public workshops</a></div><div><h3>Explore</h3><a href="blocks.html">The block map</a><a href="method.html">The method</a><a href="evidence.html">Evidence</a></div><div><h3>More</h3><a href="faq.html">FAQ</a><a href="resources.html">Resources</a><a href="../games/index.html">Playroom</a></div><div><h3>Contact</h3><a href="mailto:hello@acreativeblock.com">hello@acreativeblock.com</a><span>Lisbon &amp; online</span></div></div><div class="footer-bottom"><span>© 2026 A Creative Block</span><a href="terms.html">Terms &amp; Conditions</a></div></div></footer>';
  var grain=document.querySelector('.grain');
  if(grain){var gx=grain.getContext('2d'),gw=0,gh=0,last=0;function resize(){gw=grain.width=Math.ceil(innerWidth/3);gh=grain.height=Math.ceil(innerHeight/3)}function noise(t){if(t-last<95)return;last=t;var im=gx.createImageData(gw,gh),d=im.data;for(var i=0;i<d.length;i+=4){var n=Math.random()*255;d[i]=d[i+1]=d[i+2]=n;d[i+3]=32}gx.putImageData(im,0,0)}resize();addEventListener('resize',resize,{passive:true});(function loop(t){noise(t);requestAnimationFrame(loop)})(0)}

  var header=document.querySelector('.site-header'),toggle=document.querySelector('.menu-toggle');
  if(toggle)toggle.addEventListener('click',function(){header.classList.toggle('open');toggle.setAttribute('aria-expanded',header.classList.contains('open'))});
  document.querySelectorAll('.navbutton').forEach(function(b){b.addEventListener('click',function(e){if(innerWidth<=1050){e.preventDefault();b.parentElement.classList.toggle('open')}})});
  document.querySelectorAll('.offer-toggle,.faq-q').forEach(function(b){b.addEventListener('click',function(){b.parentElement.classList.toggle('open')})});
  var io=new IntersectionObserver(function(es){es.forEach(function(e){if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}})},{threshold:.08,rootMargin:'0px 0px -5%'});document.querySelectorAll('main section,.reveal').forEach(function(x,i){x.classList.add('reveal');x.style.transitionDelay=(i%3)*45+'ms';io.observe(x)});
  document.querySelectorAll('.newsletter').forEach(function(f){f.addEventListener('submit',function(e){e.preventDefault();var b=f.querySelector('button');b.textContent='Thank you';setTimeout(function(){b.textContent='Join'},1800)})});

  // The shared SVG script supplies the exact logo and pupil tracking. Beta adds only a
  // direct-pointer impact on BLOCK; there is deliberately no scroll listener.
  var mount=document.querySelector('[data-beta-logo]');
  if(!mount)return;
  requestAnimationFrame(function waitForLogo(){
    var svg=mount.querySelector('svg');
    if(!svg){requestAnimationFrame(waitForLogo);return}
    var paths=[].slice.call(svg.querySelectorAll('path')),pupil=svg.querySelector('circle'),letters=paths.slice(-5),eye=null;
    [].slice.call(svg.querySelectorAll('rect[clip-path]')).forEach(function(n){var m=(n.getAttribute('clip-path')||'').match(/#([^\)]+)/),cp=m&&svg.querySelector('#'+m[1]);n.remove();if(cp)cp.remove()});
    if(pupil){var pcx=+pupil.getAttribute('cx'),pcy=+pupil.getAttribute('cy');paths.forEach(function(p){var q=p.getBBox();if(pcx>=q.x&&pcx<=q.x+q.width&&pcy>=q.y&&pcy<=q.y+q.height){if(!eye||q.width*q.height<eye.area)eye={el:p,area:q.width*q.height}}})}
    var bodies=letters.map(function(el){el.style.transformBox='fill-box';el.style.transformOrigin='center';return{el:el,x:0,y:0,vx:0,vy:0,r:0,vr:0}}),raf=0;
    function tick(){var active=false;bodies.forEach(function(b){var isEye=eye&&b.el===eye.el;b.vx+=-b.x*.055;b.vy+=-b.y*.055;if(!isEye)b.vr+=-b.r*.045;b.vx*=.79;b.vy*=.79;b.vr*=.77;b.x+=b.vx;b.y+=b.vy;if(!isEye)b.r+=b.vr;else{b.r=0;b.vr=0}b.el.style.translate=b.x+'px '+b.y+'px';b.el.style.rotate=b.r+'deg';if(isEye&&pupil)pupil.style.translate=b.x+'px '+b.y+'px';if(Math.abs(b.x)+Math.abs(b.y)+Math.abs(b.vx)+Math.abs(b.vy)>.08)active=true});if(active)raf=requestAnimationFrame(tick);else raf=0}
    function hit(e){var r=svg.getBoundingClientRect(),mx=(e.clientX-r.left)/r.width*svg.viewBox.baseVal.width,my=(e.clientY-r.top)/r.height*svg.viewBox.baseVal.height;bodies.forEach(function(b){var q=b.el.getBBox(),cx=q.x+q.width/2,cy=q.y+q.height/2,dx=cx-mx,dy=cy-my,d=Math.hypot(dx,dy),isEye=eye&&b.el===eye.el;if(d<180){var f=(1-d/180)*10;b.vx+=(dx/(d||1))*f;b.vy+=(dy/(d||1))*f;if(!isEye)b.vr+=(Math.random()-.5)*4}});if(!raf)raf=requestAnimationFrame(tick)}
    // Pointer collision intentionally disabled: the brand mark remains stable.
    if(eye&&pupil){eye.el.style.transformBox='fill-box';eye.el.style.transformOrigin='center';(function blink(){setTimeout(function(){eye.el.animate([{transform:'scaleY(1)'},{transform:'scaleY(.08)',offset:.48},{transform:'scaleY(1)'}],{duration:180,easing:'cubic-bezier(.4,0,.2,1)'});pupil.animate([{opacity:1},{opacity:0,offset:.4},{opacity:0,offset:.58},{opacity:1}],{duration:180});blink()},1900+Math.random()*3600)})()}
  });
})();
